services:
  # Backend API (NestJS)
    name: ra7ba-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
        fromDatabase:
          name: ra7ba-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@ra7ba.com
      - key: ADMIN_PASSWORD
        value: Admin123!ChangeMe
      - key: CORS_ORIGINS
        value: "https://ra7ba-frontend.onrender.com,*.ra7ba-frontend.onrender.com,http://localhost:3000"
      - key: FRONTEND_URL
        value: https://ra7ba-frontend.onrender.com
    healthCheckPath: /api

  # Frontend (Next.js)
  - type: web
    name: ra7ba-frontend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://ra7ba-backend.onrender.com/api
      - key: NEXT_PUBLIC_APP_NAME
        value: Ra7ba
      - key: NEXT_PUBLIC_APP_DOMAIN
        value: ra7ba-frontend.onrender.com

# No databases needed - using Supabase
