# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl", "python3"]

[phases.install]
cmds = [
  "npm ci",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:railway"
