name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # كل 10 دقائق
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -s https://ra7ba-1.onrender.com/ > /dev/null
